"use strict";

const canvasWidth    = 620;
const canvasHeight   = 620;
const boardSize      = 8;
const tileSize       = 70;
const boardX         = 30;
const boardY         = 30;
const startingAP     = 5;
const maxActionPoints = 5;
const introHandSize   = 3;
const maxHandSize     = 4;
const maxDesperation  = 4;

const levelConfigs = [
    {
        levelNumber: 1,
        name: "Catacombs",
        backgroundImage: "Assets/Level1.png",
        normalEnemy: {
            name: "Skeleton",
            type: "skeleton",
            color: "#9b2f35",
            hp: 50,
            damage: 15,
            range: 1,
            speed: 1,
            safeZoneWeight: 1,
        },
        boss: {
            name: "Skeleton King",
            type: "boss",
            color: "#6f1d2b",
            hp: 500,
            damage: 30,
            range: 1,
            speed: 1,
            safeZoneWeight: 2,
            tileSpan: 2,
            summonEveryTurns: 2,
            moveEveryTurns: 3,
        },
        bossSummon: {
            name: "Skeleton Vanguard",
            type: "skeleton",
            color: "#7f2430",
            hp: 80,
            damage: 22,
            range: 1,
            speed: 1,
            safeZoneWeight: 1,
        },
        hordes: [
            {
                hordeNumber: 1,
                maxTurns: 10,
                enemiesPerTurn: 1,
                maxEnemiesOnBoard: 8,
                obstacleCount: 0,
                spawnEdges: ["top"],
            },
            {
                hordeNumber: 2,
                maxTurns: 15,
                enemiesPerTurn: 1,
                maxEnemiesOnBoard: 10,
                obstacleCount: 2,
                spawnEdges: ["top", "left", "right"],
            },
            {
                hordeNumber: 3,
                maxTurns: 20,
                enemiesPerTurn: 2,
                maxEnemiesOnBoard: 12,
                obstacleCount: 4,
                spawnEdges: ["top", "left", "right", "bottom"],
            },
        ],
        bossEncounter: {
            obstacleCount: 0,
        },
    },
    {
        levelNumber: 2,
        name: "Ogre Dungeon",
        backgroundImage: "Assets/Level2.png",
        normalEnemy: {
            name: "Ogre",
            type: "ogre",
            color: "#4f6b3b",
            hp: 80,
            damage: 25,
            range: 1,
            speed: 1,
            safeZoneWeight: 1,
        },
        boss: {
            name: "Ogre Boss",
            type: "ogreboss",
            color: "#314b28",
            hp: 350,
            damage: 40,
            range: 1,
            speed: 1,
            safeZoneWeight: 2,
            tileSpan: 2,
            summonEveryTurns: 2,
            moveEveryTurns: 3,
        },
        bossSummon: {
            name: "Ogre Brute",
            type: "ogre",
            color: "#3f5e32",
            hp: 100,
            damage: 30,
            range: 1,
            speed: 1,
            safeZoneWeight: 1,
        },
        hordes: [
            {
                hordeNumber: 1,
                maxTurns: 20,
                enemiesPerTurn: 1,
                maxEnemiesOnBoard: 7,
                obstacleCount: 2,
                spawnEdges: ["top", "left"],
            },
            {
                hordeNumber: 2,
                maxTurns: 26,
                enemiesPerTurn: 1,
                maxEnemiesOnBoard: 9,
                obstacleCount: 4,
                spawnEdges: ["top", "left", "right"],
            },
            {
                hordeNumber: 3,
                maxTurns: 32,
                enemiesPerTurn: 2,
                maxEnemiesOnBoard: 10,
                obstacleCount: 6,
                spawnEdges: ["top", "left", "right", "bottom"],
            },
        ],
        bossEncounter: {
            obstacleCount: 0,
        },
    },
    {
        levelNumber: 3,
        name: "Brave King's Castle",
        backgroundImage: "Assets/Level3.png",
        normalEnemy: {
            name: "Elite Warrior",
            type: "elitewarrior",
            color: "#9b6d2f",
            hp: 100,
            damage: 35,
            range: 1,
            speed: 2,
            safeZoneWeight: 1,
        },
        boss: {
            name: "Brave King",
            type: "braveking",
            color: "#8e2d25",
            hp: 500,
            damage: 50,
            range: 1,
            speed: 1,
            safeZoneWeight: 2,
            tileSpan: 2,
            summonEveryTurns: 2,
            moveEveryTurns: 3,
        },
        bossSummon: {
            name: "Royal Elite",
            type: "elitewarrior",
            color: "#b17d33",
            hp: 120,
            damage: 40,
            range: 1,
            speed: 2,
            safeZoneWeight: 1,
        },
        hordes: [
            {
                hordeNumber: 1,
                maxTurns: 20,
                enemiesPerTurn: 1,
                maxEnemiesOnBoard: 8,
                obstacleCount: 2,
                spawnEdges: ["top", "left", "right"],
            },
            {
                hordeNumber: 2,
                maxTurns: 28,
                enemiesPerTurn: 2,
                maxEnemiesOnBoard: 10,
                obstacleCount: 3,
                spawnEdges: ["top", "left", "right", "bottom"],
            },
            {
                hordeNumber: 3,
                maxTurns: 34,
                enemiesPerTurn: 2,
                maxEnemiesOnBoard: 12,
                obstacleCount: 4,
                spawnEdges: ["top", "left", "right", "bottom"],
            },
        ],
        bossEncounter: {
            obstacleCount: 0,
        },
    },
];

const keyDirections = {
    ArrowUp:    { row: -1, col:  0 },
    ArrowDown:  { row:  1, col:  0 },
    ArrowLeft:  { row:  0, col: -1 },
    ArrowRight: { row:  0, col:  1 },
    w: { row: -1, col:  0 },
    s: { row:  1, col:  0 },
    a: { row:  0, col: -1 },
    d: { row:  0, col:  1 },
    q: { row: -1, col: -1 },
    e: { row: -1, col:  1 },
    z: { row:  1, col: -1 },
    c: { row:  1, col:  1 },
};

// Upgrade tiers for ally cards — cumulative stat bonuses from base
const UPGRADE_TIERS = [
    null,
    { cost: 20, hp: 15, dmg: 10, ap: 0 },
    { cost: 40, hp: 25, dmg: 20, ap: 1 },
    { cost: 50, hp: 40, dmg: 35, ap: 2 },
];

// Card pool in case the data base is not active
const cardPool = [
    {
        name:   "Knight",
        type:   "ally",
        cost:   3,
        hp:     80,
        damage: 30,
        range:  1,
        color:  "#4677c8", 
        text:   "Melee ally. Attacks adjacent enemies.",
    },
    {
        name:   "Archer",
        type:   "ally",
        cost:   2,
        hp:     50,
        damage: 20,
        range:  3,
        color:  "#4b9d69",
        text:   "Stationary ranged ally. Range 3.",
    },
    {
        name:   "Wall",
        type:   "ally",
        cost:   3,
        hp:     150,
        damage: 0,
        range:  0,
        color:  "#7c7d82",
        text:   "Blocks a tile and absorbs attacks.",
    },
    {
        name:   "Decoy",
        type:   "ally",
        cost:   2,
        hp:     80,
        damage: 0,
        range:  0,
        color:  "#e74c3c",
        text:   "Draws all enemies toward it. No attack.",
    },
    {
        name:     "Exile",
        type:     "trap",
        cost:     2,
        duration: 2,
        color:    "#9b59b6",
        text:     "Trap. Stuns an enemy for 2 turns.",
    },
    {
        name:   "Bomb",
        type:   "zone",
        cost:   4,
        damage: 40,
        color:  "#e74c3c",
        text:   "Explodes on placement. 40 damage to all enemies in 3x3.",
    },
    {
        name:     "Peace Treaty",
        type:     "zone",
        cost:     2,
        duration: 4,
        color:    "#55b7b3",
        text:     "3x3 zone. Freezes enemies each turn for 4 turns.",
    },
    {
        name:     "Royal Curse",
        type:     "zone",
        cost:     3,
        duration: 5,
        color:    "#c0392b",
        text:     "3x3 zone. Reduces enemy damage to allies by 50% for 5 turns.",
    },
];
